// ============================================================================
// Markdown Generator — Compiles validated AnalysisResult into clean Markdown
// ============================================================================

import type { AnalysisResult, ReportMetadata } from "@/types/analysis";

/**
 * Generate a complete Markdown report from validated analysis data.
 */
export function generateMarkdownReport(
  result: AnalysisResult,
  metadata: ReportMetadata
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${metadata.projectName} — ArchLens AI Analysis`);
  lines.push("");
  lines.push(`**Date:** ${metadata.analysisDate}`);
  lines.push(`**Provider:** ${metadata.provider}`);
  lines.push(`**Model:** ${metadata.model}`);
  lines.push(`**Confidence:** ${(metadata.confidenceLevel * 100).toFixed(0)}%`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(result.summary);
  lines.push("");

  // Important UI Elements
  if (result.importantUIElements?.length > 0) {
    lines.push("## Important UI Elements");
    lines.push("");
    for (const el of result.importantUIElements) {
      lines.push(`- ${el}`);
    }
    lines.push("");
  }

  // Detected Text
  if (result.detectedText?.length > 0) {
    lines.push("## Detected Text");
    lines.push("");
    for (const text of result.detectedText) {
      lines.push(`- "${text}"`);
    }
    lines.push("");
  }

  // Problems Found
  if (result.problemsFound?.length > 0) {
    lines.push("## Problems Found");
    lines.push("");
    for (const problem of result.problemsFound) {
      lines.push(`- ⚠️ ${problem}`);
    }
    lines.push("");
  }

  // Recommended User Action
  if (result.recommendedUserAction) {
    lines.push("## Recommended Next Action");
    lines.push("");
    lines.push(result.recommendedUserAction);
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push("*Generated by [ArchLens AI](https://github.com/Shezan-op/archlens-ai) — Screenshot Intelligence Tool*");

  return lines.join("\n");
}
